php-webdriver/php-webdriver

- lib/WebDriverTargetLocator.php
Hi,
For a while, I didn't think about the library which didn't send the id parameter because it was working for Firefox, Chrome and a lot of other drivers.
However, some others required this parameter : 
* https://code.google.com/p/chromedriver/issues/detail?id=981
* https://github.com/selendroid/selendroid/issues/664
* https://github.com/operasoftware/operachromiumdriver/issues/2
In fact, we must send a NULL parameter to fix it, just like the java client do : 
https://code.google.com/p/selenium/source/browse/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#886
and it is supported by the protocol : 
https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/frame
With this new parameter, no regression has been detected for FF, Chrome, HTMLunit, PhantomJS, …
> fix switch to main document

- composer.json
- lib/remote/HttpCommandExecutor.php
Our version of PHP (5.3.3) was giving an expects 'long' not string error. I know this is an officially unsupported version. We're locked in by our shared platform. 
This is more for reference.
> Correct curl value for CURLOPT_TIMEOUT_MS

- lib/chrome/ChromeDriver.php
- lib/remote/RemoteWebDriver.php
Previously you could only set the request timeout after the first
request (NEW_SESSION) was sent. If you want to alter the timeout, you
presumably want to affect the first request too.
> RemoteWebDriver: Allow specifying request timeout

- lib/WebDriverSelect.php
Fixed the current implementation of strpos, it currently looked like this
`strpos($to_escape, "'" != false))` incorrectly passes `"'" != false` as the second argument.
Changed it to `if (strpos($to_escape, '"') !== false && strpos($to_escape, "'") !== false) {`
> Fixed strpos: ending parentheses is in incorrect location

- lib/remote/RemoteWebElement.php
`newElement` uses the actual class' constructor to create new objects.
An alternative would have been to make the method protected (it is now private).
This change enables users to extend the `RemoteWebElement` API by subclassing it.
> Made RemoteWebElement extendable

- .travis.yml
> Fix: Update Composer binary in before_install section

- .travis.yml
This PR
:information_desk_person: This should help speeding up builds.
> Enhancement: Cache dependencies installed with Composer between Travis builds

- .travis.yml
This PR
Related to https://github.com/facebook/php-webdriver/pull/228.
:information_desk_person: This should speed up builds, too.
> Enhancement: Direct Travis builds to container-based infrastructure

- lib/Remote/DesiredCapabilities.php
This tooltip can hide window.document elements, which can break tests.
See http://stackoverflow.com/questions/30764805/how-to-disable-reader-view-in-firefox-using-webdriver
> Disable Firefox Reader View help tooltip

- lib/Remote/RemoteWebDriver.php
- lib/Remote/RemoteWebElement.php
- lib/Support/Events/EventFiringWebDriver.php
- lib/Support/Events/EventFiringWebElement.php
Previously, if a developer wanted to extend the RemoteWebElement()
class, you couldn't effectively do it (#217 got us part of the way).
The name of the class was hard-coded in a private factory
method of RemoteWebDriver that couldn't be overriden.
Now, a custom class that extends RemoteWebDriver can
construct a class derived from RemoteWebElement, allowing
extra functionality to be added to Elements themselves.
The same logic applies to the EventFiringWebElement.
> RemoteWebElement: allow overriding construction

- lib/Firefox/FirefoxProfile.php
During profile setup, some temporary files/folders are created. These temporary files/folders can grow quite large, so clean them up after the profile has been constructed to prevent disk space issues.
> FirefoxProfile: clean up temporary files

- lib/Firefox/FirefoxProfile.php
- lib/Remote/RemoteWebElement.php
The latter fails when using the empty string if an open_basedir restriction is
in effect.
Also refer to https://secure.php.net/manual/en/function.tempnam.php#93256
> Use sys_get_temp_dir rather than the empty string when calling tempnam.

- lib/Chrome/ChromeDriver.php
Running tests currently causes following strict standards error for us:
> PHP Strict standards:  Declaration of Facebook\WebDriver\Chrome\ChromeDriver::create() should be compatible with Facebook\WebDriver\Remote\RemoteWebDriver::create($url = 'http://loc...', $desired_capabilities = NULL, $connection_timeout_in_ms = NULL, $request_timeout_in_ms = NULL, $http_proxy = NULL, $http_proxy_port = NULL) in .../vendor/facebook/webdriver/lib/Chrome/ChromeDriver.php on line 89
Though we do not use `ChromeDriver::create()` method (and it cannot be used either), it still must have compatible signature with the `RemoteWebDriver::create()` method (because `ChromeDriver` is extending `RemoteWebDriver`).
This PR updates the method declaration to match those in `RemoteWebDriver::create()`.
> Fix strict standards error in ChromeDriver

- lib/Interactions/WebDriverActions.php
With the update in Selenium https://github.com/SeleniumHQ/selenium/issues/1202 the moveToElement function is going to take more relevance. I thought that the current description could lead to misunderstandings and decided to improve it a bit. I hope you find it more accurate.
> Enhance moveToElement method description

- lib/Firefox/FirefoxProfile.php
Update to make extractTo() throw an exception if the Firefox extension .xpi file doesn't exist, which should be the desired behavior.
Currently extractTo() only throws an error if the .xpi file exists AND is unable to open.
ZipArchive throws some Warning messages when you use extractTo() and close() on an initialized ZipArchive object which is the case if the file doesn't exist.
> Throw exception if XPI extension file doesn't exist.

- lib/Remote/RemoteWebDriver.php
This PR fixes the issue noted at https://github.com/facebook/php-webdriver/issues/254
It's possible for 
$this->executor
to be null at the time that this method is called, resulting in a PHP Fatal Error.
It is readily replicated within Codeception when an element cannot be found.  There's an issue over at Codeception https://github.com/Codeception/Codeception/issues/518 for this, but it's really a problem with RemoteWebDriver and not Codeception's consuming class. 
This PR adds a check for this condition and avoids the Fatal Error.
> Fixed PHP Fatal crash in RemoteWebDriver:507

- CHANGELOG.md
- lib/Remote/DesiredCapabilities.php
- lib/Remote/WebDriverBrowserType.php
- tests/unit/Remote/DesiredCapabilitiesTest.php
This adds basic Microsoft Edge support - ie. only when Edge is used as a node. It still does not support starting Microsoft WebDriver executable locally - as it is [supported by eg. the official Java bindings ](https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/java/client/src/org/openqa/selenium/edge/EdgeDriverService.java), because this would require implementing the `EdgeDriverService` (which would extend `DriverService`, similary as [`ChromeDriverService` does](https://github.com/facebook/php-webdriver/blob/b7186fb1bcfda956d237f59face250d06ef47253/lib/Chrome/ChromeDriverService.php)). So the issue  #244 is still partially valid. But as a Linux user this full support would be quite difficult for me to implement and especially test - help from Windows …
> Initial Microsoft Edge support

- lib/Chrome/ChromeDriverService.php
- lib/Remote/DesiredCapabilities.php
- lib/WebDriverBy.php
- lib/WebDriverExpectedCondition.php
I came across the issue when I was trying to extend `WebDriverBy` class, it uses a whole bunch of `new self(...)` statements which restricts the extension by other classes. The same is for a few other classes.  
This PR aims to fix the issue across all affected classes by utilizing late static binding (`new static`) instead. LSB is introduced in PHP 5.3 which meets project's PHP version requirements.
This also addresses #285.
> Utilize late static binding

- composer.json
- lib/Remote/HttpCommandExecutor.php
- tests/unit/Remote/HttpCommandExecutorTest.php
Do not set URL placeholder params as part of POST body. This fixes incompatibility with Appium, caused by redundant params present in requests to Selenium server.
See #323.
> Fixes incompatibility with Appium

- composer.json
- lib/Remote/Service/DriverService.php
As in #299, I was unable to start ChromeDriver directly (ie. without Selenium server) and I also have no luck determining the cause (the process got stuck somehow). I was able to fix it by replacing the `proc_open()` with [Symfony Process component](https://symfony.com/doc/current/components/process.html). 
The Process component itself uses the proc_open(), however, it adds compatibility layer, worarounds for some [PHP bugs](https://github.com/php/php-src/pull/1588) and encapsulates the whole started process, so it can be easily manipulated (and started asynchronously).
Even though I cannot verify it fixes #299, it makes starting of the process more portable. What do others think?
> Use Symfony Process component to start local webdriver processes

- lib/Net/URLChecker.php
In the URLChecker class, the $timeout_in_ms value is not used by the getHTTPResponseCode() method.
To check the timeout, the same method uses two other value, the  language constant **CURLOPT_CONNECTTIMEOUT_M**S and the class constant **self::CONNECT_TIMEOUT_MS**
> Fix unused code in the URLChecker class

- CHANGELOG.md
- lib/Chrome/ChromeDriver.php
- lib/Remote/HttpCommandExecutor.php
- lib/Remote/RemoteWebDriver.php
- lib/Remote/Service/DriverCommandExecutor.php
- lib/WebDriverCommandExecutor.php
- tests/functional/FileUploadTest.php
- tests/functional/RemoteWebDriverCreateTest.php
- tests/functional/RemoteWebDriverFindElementTest.php
- tests/functional/RemoteWebDriverTest.php
- tests/functional/RemoteWebElementTest.php
- tests/functional/WebDriverByTest.php
- tests/functional/WebDriverTestCase.php
Required capabilities are present for a long time in eg. Java bindings. And they are also part of the WebDriver W3C specification - see https://w3c.github.io/webdriver/webdriver-spec.html#processing-capabilities .
Currently Selenium server accept them only as part of `desiredCapabilities`; in future (when this part of the W3C spec will be implemented in Selenium) they will be passed in a different way (in `alwaysMatch` and `firstMatch` properties) - however it will be just an implementation change, with no impact to end users calling the `RemoteWebDriver::create`.
This will also help to workaround #334.
> Support required capabilities

- CHANGELOG.md
- lib/WebDriverExpectedCondition.php
- tests/functional/RemoteWebDriverTest.php
- tests/unit/WebDriverExpectedConditionTest.php
Inspired by official Java, Python and Javascript bindings, following new expected conditions were added:
- `titleMatches`
- `elementTextIs`
- `elementTextMatches`
- `elementTextContains` (as an alias for `textToBePresentInElement`)
- `numberOfWindowsToBe`
Also, in #370, the urlIs, urlContains and maybe urlMatches conditions will be added as well.
For consistency, I also suggest deprecating the `textToBePresentInElement()` condition in favor of the `elementTextContains`. It s IMHO easier to find with code-completion in IDE, and the naming will be much more systematic and readable:
- elementText[Is, Matches, Contains]
- title[Is, Matches, Contains]
- url[Is, Matches, Contains]
What does other think about this change?
> Add new expected conditions + unit tests

- CHANGELOG.md
- lib/Support/XPathEscaper.php
- lib/WebDriverSelect.php
- lib/WebDriverSelectInterface.php
- tests/functional/WebDriverSelectTest.php
- tests/functional/web/form.html
- tests/unit/Support/XPathEscaperTest.php
- Replaces #376, fixes #375, also adds `deselectByVisiblePartialText` method as a counterpart to the new `selectByVisiblePartialText`
- Functional tests for all WebDriverSelect methods were added
- XPath escaping which was present wasn't actually working (though nobody notices it for ages 🤔), not it should be and could by also called from user scripts
- Some refactoring and DRY
> Select enhacements

- CHANGELOG.md
- lib/WebDriverSelect.php
Single select always contains exactly only one selected option.
> Optimize getAllSelectedOptions method for single select

- composer.json
While trying to run this example (https://github.com/facebook/php-webdriver/wiki/upload-a-file) I ran into a problem of ZipArchive class not being found. Fixed it by doing `sudo apt-get install php7.1-zip`
> Added ext-zip to require section of composer.json

- CHANGELOG.md
- lib/Remote/DesiredCapabilities.php
- lib/WebDriverCapabilities.php
It was deprecated in the Java client version 3.3.1 as well.
See https://github.com/SeleniumHQ/selenium/commit/5b0f88ef3256595148b357dec6209735cab25bea
> Deprecate isJavascriptEnabled method of WebDriverCapabilities

- CHANGELOG.md
- lib/WebDriverExpectedCondition.php
- tests/unit/WebDriverExpectedConditionTest.php
...  in favor of `elementValueContains()`. This makes the name consistent with other expected conditions.
> Deprecate text to be present in element value

- lib/Net/URLChecker.php
Prior to this change I would be getting `Constant CURLOPT_CONNECTTIMEOUT_MS already defined` since PHP would try to re-define a constant.
> Correct constant checking

- LICENCE.md
The licence is already defined in header of all files (and is also stated on packagist). However adding the licence text directly to the repository is more standard, as Github will recognize it by itself, add it to the repository header etc.
> Add LICENCE.md

- .travis.yml
- CHANGELOG.md
- lib/Support/Events/EventFiringWebDriver.php
- lib/Support/Events/EventFiringWebDriverNavigation.php
- lib/Support/Events/EventFiringWebElement.php
Anyone against dropping support of PHP 5.5?
It blocks using some newer version of other libraries (PHPUnit etc.), is no longer officially supported [for over a year](http://php.net/eol.php) and its [usage also drops dramatically](https://seld.be/notes/php-versions-stats-2017-1-edition) in the last year.
Of course anyone relying on PHP 5.5 could still use all versions preceding the one which will contain this change, so I guess this should not by an issue for anyone.
> Drop PHP 5.5 support

- CHANGELOG.md
- lib/WebDriverExpectedCondition.php
- tests/unit/WebDriverExpectedConditionTest.php
This pull request adds a new visibilityOfAnyElementsLocated method to WebDriverExpectedCondition. This condition checks to see if any elements in an array of located elements are visible, not just the first one. This condition also returns an array of all elements that meet the criteria and are located and visible.
> Adding WebDriverExpectedCondition::visibilityOfAnyElementsLocated

- composer.json
- tests/functional/Chrome/ChromeDriverServiceTest.php
- tests/functional/Chrome/ChromeDriverTest.php
- tests/functional/ReportSauceLabsStatusListener.php
- tests/functional/WebDriverTestCase.php
- tests/unit/CookieTest.php
- tests/unit/Exception/WebDriverExceptionTest.php
- tests/unit/Interactions/Internal/WebDriverButtonReleaseActionTest.php
- tests/unit/Interactions/Internal/WebDriverClickActionTest.php
- tests/unit/Interactions/Internal/WebDriverClickAndHoldActionTest.php
- tests/unit/Interactions/Internal/WebDriverContextClickActionTest.php
- tests/unit/Interactions/Internal/WebDriverCoordinatesTest.php
- tests/unit/Interactions/Internal/WebDriverDoubleClickActionTest.php
- tests/unit/Interactions/Internal/WebDriverKeyDownActionTest.php
- tests/unit/Interactions/Internal/WebDriverKeyUpActionTest.php
- tests/unit/Interactions/Internal/WebDriverMouseMoveActionTest.php
- tests/unit/Interactions/Internal/WebDriverMouseToOffsetActionTest.php
- tests/unit/Interactions/Internal/WebDriverSendKeysActionTest.php
- tests/unit/Remote/DesiredCapabilitiesTest.php
- tests/unit/Remote/HttpCommandExecutorTest.php
- tests/unit/Remote/RemoteWebDriverTest.php
- tests/unit/Remote/RemoteWebElementTest.php
- tests/unit/Remote/WebDriverCommandTest.php
- tests/unit/Support/XPathEscaperTest.php
- tests/unit/WebDriverExpectedConditionTest.php
- tests/unit/WebDriverKeysTest.php
- tests/unit/WebDriverOptionsTest.php
Use [PSR-1](http://www.php-fig.org/psr/psr-1/#namespace-and-class-names) while extending PHPUnit TestCase class. This will help us when to migrate to PHPUnit 6, that [no longer support snake case namespaces](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
> Use PSR-1 for PHPUnit TestCase

- composer.json
- lib/Remote/Service/DriverService.php
Symfony4 is in beta now and I think that it's time to allow developers test theirs projects with new set of components. But php-webdriver blocks install some of its. This PR allow.
> Allow Symfony4 components

- CHANGELOG.md
- lib/Remote/HttpCommandExecutor.php
- tests/functional/ReportSauceLabsStatusListener.php
- tests/unit/Remote/HttpCommandExecutorTest.php
This pull-request solves strict RFC HTTP/1.1 https://tools.ietf.org/html/rfc7231#section-5.1.1 behavior.
If you are communicating with a server on HTTP/1.0 old behavior is ok. But if HTTP/1.1 is used, by RFC HTTP 417 should be returned. This will probably will work on most cases, but in combination with squid proxy, you will be forced to solve it on app site.
HTTP Expect: 100-continue is added when `curl_setopt($this->curl, CURLOPT_POSTFIELDS, $encoded_params);` with not null `$encoded_params` present.
> add reply request without 100-continue expectation

- CHANGELOG.md
- lib/Chrome/ChromeDriver.php
- lib/Chrome/ChromeDriverService.php
- lib/Remote/DesiredCapabilities.php
- lib/Remote/RemoteWebDriver.php
- lib/Remote/RemoteWebElement.php
- lib/Support/Events/EventFiringWebElement.php
- lib/WebDriverBy.php
- lib/WebDriverExpectedCondition.php
Previously, functions that contained functionality similar to `return new static(...)` had their `@return` PHPDoc tag to specify the class name like `@return SomeClass` where the preferred documentation should be `@return static`.
Some support for this decision:
https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#keyword
https://netbeans.org/bugzilla/show_bug.cgi?id=196565
https://blog.madewithlove.be/post/return-types/
> Update PHPDoc for functions that return static instances of a class

- lib/WebDriverOptions.php
`Cookie` should be either absolute (starting with `\`) or relative to be clickable in PHPStorm.
> Fix @see in WebDriverOptions::addCookie

- .travis.yml
- tests/functional/RemoteWebDriverTest.php
- tests/functional/WebDriverActionsTest.php
- tests/functional/WebDriverTestCase.php
- tests/functional/WebDriverTimeoutsTest.php
- tests/functional/web/delayed_element.html
First part of some house-keeping.
Simplify doubleClick test to make it temporarily working, as this action is not part of W3C WebDriver.
Also, upgrade to Edge 16.
> Improve test stability on SauceLabs

- .travis.yml
- lib/Remote/HttpCommandExecutor.php
- lib/Remote/RemoteWebDriver.php
Chromedriver 75 released together with Chrome 75 on 4th June 2019 uses W3C WebDriver protocol [by default](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2536). 
But php-webdriver does not (see #469) support this protocol yet, so this hotfix disables the W3C WebDriver protocol and re-enables the old one JsonWire aka OSS.
Unfortunately, this change in Chromedriver 75 accidentally broke the old JsonWire protocol, so just disabling the new protocol is not enough :-/. See Chromedriver bug [2943](https://bugs.chromium.org/p/chromedriver/issues/detail?id=2943). The bug causes Chromedriver to require at least some data in POST body request (what should not be required in JsonWire protocol). So as a workaround for the Chromedriver bug, we are adding some dummy data in the body (as …
> Disable W3C protocol in Chrome 75+

- lib/Cookie.php
- tests/unit/CookieTest.php
Both JsonWireProtocol and w3c protocol say to leave an entry off
rather than having a null value.
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol
https://w3c.github.io/webdriver/#add-cookie
> 626 no null values in cookie

- lib/Remote/DesiredCapabilities.php
- lib/Remote/RemoteWebDriver.php
- tests/functional/RemoteWebDriverCreateTest.php
Close #642 
DesiredCapabilities#toArray() is a mutable operation which can lead to undesirable side effect. Cloning the instance before calling it will prevent this.
Exemple of side effect : 
```php
<?php
use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\DesiredCapabilities;
require __DIR__.'/vendor/autoload.php';
$capabilities = new DesiredCapabilities();
$capabilities->setCapability(ChromeOptions::CAPABILITY, new ChromeOptions());
$options = $capabilities->getCapability(ChromeOptions::CAPABILITY); // Instance of Facebook\WebDriver\Chrome\ChromeOptions
$capabilities->toArray();
$options = $capabilities->getCapability(ChromeOptions::CAPABILITY); // Oh no it's an array
```
> Fix regression in 1.7.0 - call to a member function toArray() on array

- lib/Remote/RemoteWebDriver.php
> Do not send w3c capability as a workaround for browsestack schema validation

- .travis.yml
- CHANGELOG.md
- lib/Remote/HttpCommandExecutor.php
Reverts #644 & #645, because workaround is no longer needed since chrome 75.0.3770.90.
Also make chrome tests on Travis use automatically the latest chromedriver binary.
> Revert chromedriver workaround

- CHANGELOG.md
- composer.json
Symfony 5 is about to be released, this PR allows to use PHP WebDriver (and so Panther) with it. There is no code changes, the new version only has to be allowed in `composer.json`.
@OndraM could you tag a new release after merging please 🙏?
> Compatibility with Symfony 5

- .travis.yml
- CONTRIBUTING.md
- lib/AbstractWebDriverCheckboxOrRadio.php
- lib/Cookie.php
- lib/Exception/WebDriverException.php
- lib/Interactions/WebDriverActions.php
- lib/Remote/DriverCommand.php
- lib/Remote/HttpCommandExecutor.php
- lib/Remote/JsonWireCompat.php
- lib/Remote/RemoteMouse.php
- lib/Remote/RemoteTargetLocator.php
- lib/Remote/RemoteWebDriver.php
- lib/Remote/RemoteWebElement.php
- lib/WebDriverDimension.php
- lib/WebDriverOptions.php
- lib/WebDriverPoint.php
- lib/WebDriverTimeouts.php
- tests/functional/RemoteWebDriverCreateTest.php
- tests/functional/RemoteWebDriverFindElementTest.php
- tests/functional/RemoteWebDriverTest.php
- tests/functional/RemoteWebElementTest.php
- tests/functional/WebDriverActionsTest.php
- tests/functional/WebDriverTestCase.php
- tests/functional/web/escape_css.html
- tests/functional/web/upload.html
This PR provides an implementation of [the W3C flavor of the WebDriver protocol](https://www.w3.org/TR/webdriver/).This implem is good enough to make the [Symfony Panther](https://github.com/symfony/panther)'s test suite green when using the latest version of [geckodriver](https://github.com/mozilla/geckodriver).
It is 100% backward compatible with the current (JsonWire) implementation.
The (only?) missing part is the capabilities support. It's a step to close #469.
TODO:
Subsequent work (in other PRs?):
* Add new classes for exceptions that wasn't part of JsonWire
* Add support for capabilities and other missing parts
> W3C-compliant implementation, native geckodriver support

- CHANGELOG.md
- lib/WebDriverExpectedCondition.php
- tests/unit/WebDriverExpectedConditionTest.php
Currently doing something like the following will cause a PhpUnit test to fail due to an exception thrown by the `presenceOfElementLocated()` call when the element is not present:
```
$driver->wait()->until(
WebDriverExpectedCondition::not(
WebDriverExpectedCondition::presenceOfElementLocated(
WebDriverBy::cssSelector('iframe[name="modal"]')
)
)
);
```
This pull request is intended to fix this problem.
Rebased against latest master as previous pull request appears to have failed travis build due to saucelabs timeout.
> Allow combined not() and presenceOfElementLocated() functionality

- composer.json
So, more users will be able to use the project.
> Use polyfill-mbstring when ext-mbstring isn't available

- .travis.yml
- lib/Chrome/ChromeOptions.php
- lib/Remote/RemoteWebDriver.php
This workaround resolves issue which emerged after #560 .
Newer Selenium servers reject `chromeOptions` key in capabilities, because it does not contain vendor prefix, what is required as per W3C protocol. However simply updating the prefix would break on the other hand older Chromedrivers - and we want to maintain BC with version 1 of this library.
Ref. #652 #551 #573 #469
> Make chromeOptions compatible with both JsonWire and W3C protocols

- .travis.yml
- lib/Remote/RemoteWebDriver.php
- tests/functional/RemoteWebDriverFindElementTest.php
- tests/functional/RemoteWebDriverTest.php
- tests/functional/RemoteWebElementTest.php
- tests/functional/WebDriverActionsTest.php
- tests/functional/WebDriverTestCase.php
W3C protocol was forced to be disabled when using Chrome (#640).
But now we can remove this and let the handshake added in #560 to determine the proper protocol to use. So starting to next release of php-webdriver (1.8.0), W3C protocol will be used be default when used with Chromedriver 75+ (and also with Firefox+Geckodriver). 
In case of troubles this could be still disabled using capabilities (as we do in on travis build):
```php
$chromeOptions = new ChromeOptions();
$chromeOptions->setExperimentalOption('w3c', false);
$capabilities = DesiredCapabilities::chrome();
$capabilities->setCapability(ChromeOptions::CAPABILITY, $chromeOptions);
$driver = RemoteWebDriver::create($hostUrl, $capabilities);
```
> Enable W3C protocol for Chrome 🎉

- lib/Remote/DesiredCapabilities.php
- lib/Remote/RemoteWebDriver.php
- tests/unit/Remote/DesiredCapabilitiesTest.php
This fixes #676 and is part of #469.
The aim is to convert non-W3C compliant capabilities to their W3C counterparts.
No change in current code is needed - you still set the "old" capabilities and the new ones get converted automatically before browser session creation.  However if you already set the new ones, you are ok as well (if you use only W3C-compatible remote browsers). 
In php-webdrver 2.0 (#657) the `DesiredCapabilities` will get revamped so that it only support W3C capabilities (and no conversion will be needed).
> Convert Capabilities to W3C compatible

- lib/Remote/RemoteMouse.php
- tests/functional/WebDriverActionsTest.php
I just discovered that the mouseUp MouseAction was actually calling pointerDown instead of pointerUp.
Fixed and provided with a new unit test.
> Correct mouseUp W3C Action

- lib/Remote/RemoteTargetLocator.php
- lib/Remote/RemoteWebDriver.php
- tests/functional/RemoteTargetLocatorTest.php
- tests/functional/WebDriverAlertTest.php
- tests/functional/web/index.html
- tests/functional/web/open_new_window.html
https://www.w3.org/TR/webdriver/#switch-to-window
> Let handle be the result of getting the property "handle" from the parameters argument.
Apologies but I'm not quite sure how best to unit test this.
> Switch to window takes a handle

- lib/Remote/HttpCommandExecutor.php
- tests/functional/RemoteTargetLocatorTest.php
As defined in the specification 12.2.6:
HTTP Method   URI Template
GET           /session/{session id}/element/active
Source: https://www.w3.org/TR/webdriver/#get-active-element
> Make ActiveElement endpoint W3C compatible

- lib/Remote/RemoteTargetLocator.php
- tests/functional/RemoteTargetLocatorTest.php
- tests/functional/WebDriverTestCase.php
- tests/functional/web/iframe_content.html
- tests/functional/web/page_with_frame.html
Frame switching W3C Compliance
This change updates the frame functionality to comply with the W3C
specification.
Valid values of the `id` parameter are:
- null
- a Number between 0 and 2^16
- an Object representing a Web element
When the value is null, set the current browsing context to the current
top-level browsing context
When the value is a valid Number, let window be the associated window of
the current browsing context’s active document.
When the value is an Object, let element be the result of trying to get
a known element by web element reference id.
Source: https://www.w3.org/TR/webdriver/#switch-to-frame
I have also included a second commit, shared with #681 to pass isW3cCompliant to the constructor as we do in other classes.
> Frame switching W3C Compliance

- CHANGELOG.md
- lib/Remote/HttpCommandExecutor.php
- lib/Remote/RemoteStatus.php
- lib/Remote/RemoteWebDriver.php
- tests/functional/RemoteWebDriverTest.php
Replaces #648 .
The status response is returned in `RemoteStatus` value object.
> Add status command

- tests/functional/WebDriverTestCase.php
To allow me to test using docker images, I have to manually edit the `getTestPgeUrl` function in the Driver testcase.
This is just a small change to allow the fixtures host to be specified as an environment variable called `FIXTURES_HOST`.
> Allow specification of alternate host for fixtures

- tests/functional/WebDriverTestCase.php
Note: This just allows us to specify options like headless.
I have not:
* fixed the `skipForJsonWireProtocol` issue . I think that we need a non-static version of these functions which checks the W3C attribute of the driver instance.
* added any new options. I was tempted to add `['log' => ['level' => 'trace']]` to aid debugging. Currently I"m adding that manually
> Allow specification of firefox options for non-gecko

- lib/Remote/RemoteWebElement.php
This _may_ fix #704 and also resolve the issue mentioned in https://github.com/facebook/php-webdriver/pull/691#issuecomment-559883408 . 
@dunglas We are not sure why the actions sequence was there in the first place, do you remember why you add it? (Test pass even without it.)
Cc @andrewnicols @romaricdrigon - could you guys try, if it fixes the issues for you? 
`composer require facebook/webdriver:dev-w3c-clear@dev`
> Use clear endpoint to clear element content even in W3C mode

- CHANGELOG.md
- lib/Remote/DriverCommand.php
- lib/Remote/HttpCommandExecutor.php
- lib/WebDriverOptions.php
- tests/functional/WebDriverOptionsCookiesTest.php
In W3C mode we can use the new `get named cookie` command instead of receiving all cookies and just filtering the one with corresponding name.
Ref. #683
> Use W3C command to get named cookie

- tests/functional/WebDriverTestCase.php
Chromedriver on Travis got crazy lately for no obvious reason. This should help us keeping stability of the builds.
PHPUnit 7.3+ has feature to rerun failed tests builtin, however, because of PHP 5.6, we cannot upgrade PHPUnit - so we must implement this ourselves.
> Rerun failed tests to improve build stability

- CHANGELOG.md
- lib/Remote/LocalFileDetector.php
- lib/Remote/RemoteWebElement.php
```
Facebook\WebDriver\Exception\UnknownErrorException : unknown error: path is not canonical: /Users/oandreyev/Development/MinkFacebookWebDriver/vendor/mink/driver-testsuite/tests/Js/../../web-fixtures/file1.txt
(Session info: chrome=79.0.3945.88)
/Users/oandreyev/Development/MinkFacebookWebDriver/vendor/facebook/webdriver/lib/Exception/WebDriverException.php:152
/Users/oandreyev/Development/MinkFacebookWebDriver/vendor/facebook/webdriver/lib/Remote/HttpCommandExecutor.php:390
/Users/oandreyev/Development/MinkFacebookWebDriver/vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php:597
/Users/oandreyev/Development/MinkFacebookWebDriver/vendor/facebook/webdriver/lib/Remote/RemoteExecuteMethod.php:40
/Users/oandreyev/Development/MinkFacebookWebDriver/vendor/facebook/webdriver/lib/Remote/Re …
```
> fixing "unknown error: path is not canonical"

- .travis.yml
- lib/Remote/DriverCommand.php
- lib/Remote/HttpCommandExecutor.php
- lib/WebDriverOptions.php
- lib/WebDriverWindow.php
- tests/functional/WebDriverWindowTest.php
Add the minimizeWindow command:
11.8.4 Minimize Window
`POST  /session/{session id}/window/minimize`
Note: There is a bug in chrome/chromedriver which prevents the visibilityState from being checked in headless mode. I've reported that in https://bugs.chromium.org/p/chromedriver/issues/detail?id=3275 and have added it to a new exclude-group for phpunit.
> Minimize window

- lib/Remote/DesiredCapabilities.php
- lib/WebDriverPlatform.php
- tests/unit/Remote/DesiredCapabilitiesTest.php
"ANY" is no longer a meaningful value for platformName in W3C mode - see [specs](https://w3c.github.io/webdriver/#x7-2-processing-capabilities).
Moreover it causes geckodriver to reject creating new session when present:
> SessionNotCreatedException: Unable to find a matching set of capabilities
May replace #703
> Remove 'any' when present in W3C platformName capabilitites

- CHANGELOG.md
- README.md
- composer.json
Once this is merged, I will mark [facebook/webdriver](https://packagist.org/packages/facebook/webdriver) package abandoned and replaced by this one :tada:
> Rename Packagist package to php-webdriver/webdriver

- lib/Remote/DriverCommand.php
- lib/Remote/HttpCommandExecutor.php
- lib/WebDriverWindow.php
- tests/functional/WebDriverWindowTest.php
I've included an extra commit here because the W3C mode doesn't take any arguments but JSONWire does but we were still including the args still.
> Fullscreen window

- CHANGELOG.md
- lib/Remote/CustomWebDriverCommand.php
- lib/Remote/DriverCommand.php
- lib/Remote/HttpCommandExecutor.php
- lib/Remote/RemoteWebDriver.php
- lib/Remote/WebDriverCommand.php
- tests/unit/Remote/CustomWebDriverCommandTest.php
- tests/unit/Remote/HttpCommandExecutorTest.php
- tests/unit/Remote/WebDriverCommandTest.php
Alternative implementation of Custom Commands, based on #611 .
The changes were only internal refactoring, so the usage is exactly the same as in #611:
```php
$clipboard = $driver->executeCustomCommand(
'/session/:sessionId/appium/device/get_clipboard/',
'POST'
);
```
> Custom commands support (v2)

- tests/functional/WebDriverWindowTest.php
Chrome / Chromedriver 80 is out, and it did break some things 🤷 - fullscreen test is failing since in headless mode.
https://bugs.chromium.org/p/chromium/issues/detail?id=1049336
> Exclude fullscreen test from chrome

- lib/Remote/RemoteWebElement.php
Hello, I've prepared a fix for an issue related to the new version of the PHP zip module. It was discussed in an open issue on the repository codeception/codeception, [link](https://github.com/Codeception/Codeception/issues/5838) to the issue.
In short, if we run codeception tests with Libzip 1.6 ZipArchive will fail to open the temp file and return error code 19.
This PR will instead let ZipArchive directly create the file for us.
> Let ZipArchive handle the creation of the zip files

- tests/functional/RemoteWebDriverCreateTest.php
Edge on SauceLabs started to identify itself as "msedge" when reading returned capabilitites - don't know why it was changed. However it breaks the test, which expects "MicrosoftEdge".
> Fix Edge builds on Sauce Labs

- CHANGELOG.md
- lib/Interactions/WebDriverActions.php
- lib/Remote/RemoteMouse.php
- tests/functional/RemoteKeyboardTest.php
- tests/functional/RetrieveEventsTrait.php
- tests/functional/WebDriverActionsTest.php
- tests/functional/web/events.html
- tests/functional/web/index.html
- tests/functional/web/sortable.html
To preserve JsonWire protocol behavior when moving a mouse pointer we need to use relative offset via `origin` action property set to `pointer`. Fixes #757 .
https://w3c.github.io/webdriver/#dfn-dispatch-a-pointermove-action
I also added some functional tests for actions.
> Fix move action in W3C mode

- CHANGELOG.md
- lib/Remote/RemoteWebElement.php
- tests/functional/RemoteWebElementTest.php
Element `/equals` endpoint is not part of the W3C protocol, however it could be easily reimplemented client-side by comparing element ids, making `equals()` working again.
Ref. https://github.com/laravel/dusk/issues/736
> Reimplement element equals method for W3C mode

- CHANGELOG.md
- lib/Remote/RemoteWebDriver.php
- phpstan.neon
- tests/functional/RemoteWebDriverCreateTest.php
Fixes #771.
When using `createBySessionID()`, I didn't find simple and reliable way how to programatically determine whether the existing browser instance is in W3C/JsonWire mode, so it must be told via fifth parameter.
Two changes happend here:
- The method incorrectly read fourth parameter instead of fifth, making it impossible to override the default (JsonWire) mode
- The mode is now by default W3C when using  `createBySessionID()` - its because W3C mode is also enabled by default in `create()` method, so I think we can assume most people will now use the W3C mode. And if they do not (or they don't know or use both modes on different browsers, like we do in functional tests), they can save value of `isW3cCompliant()` and provide it via fifth parameter - [see …
> Fix creating driver from session ID

- lib/Firefox/FirefoxProfile.php
Firefox support is currently not working on Mac OS Catalina because of https://bugs.php.net/bug.php?id=79296. This PR introduces a workaround to make it working.
> Fix Firefox support on Mac OS Catalina

- lib/Firefox/FirefoxPreferences.php
- lib/Remote/DesiredCapabilities.php
By default, Firefox's JSONView is enabled, which causes issue when trying to parse a JSON response.
For instance, a JSON like this:
```json
{
"id": 1,
"className": "App\\User"
}
```
Would be rendered with lot of HTML in the source like the screenshot below:
To fix the issue, we currently have to disable the preference manually:
```php
$caps = DesiredCapabilities::firefox();
$profile = new FirefoxProfile;
$profile->setPreference('devtools.jsonview.enabled', false);
$profile->setPreference(FirefoxPreferences::READER_PARSE_ON_LOAD_ENABLED, false);
$caps->setCapability(FirefoxDriver::PROFILE, $profile);
```
> Disable the Devtools JSONView

- composer.json
If ones subdependency requires facebook/webdriver, composer will try to require both php-webdriver/webdriver and facebook/webdriver, which will cause namespace conflicts, as shown in #780.
See https://getcomposer.org/doc/04-schema.md#replace
> Mark package replacing facebook/webdriver (fixes #780)

- lib/WebDriverExpectedCondition.php
- tests/functional/WebDriverAlertTest.php
- tests/functional/web/alert.html
The catched exception was swapped. We can rely on `NoSuchAlertException` (w3c exception), because it catches also `NoAlertOpenException` (oss mode exception), as it is inherited from `NoSuchAlertException`.
> Fix alertIsPresent in W3C mode

- lib/Chrome/ChromeDriver.php
The `new static` within `ChromeDriver::start()` creates a RemoteWebDriver that is not W3C compatible by default (due to the default for RemoteWebDriver's 4th constructor arg). The command executor it uses assumes W3C compatibility by default though. This causes strange bugs, where commands are created assuming non-compliance, but translated by the command executor as if they were W3C compliant.
By using the logic already present in `RemoteWebDriver::create()`, ChromeDriver now detects whether the session it started is in W3C compatible mode and updates the flags both on itself and on its executor.
> Fix ChromeDriver::start() causes 'mixed' W3c mode

- .github/CONTRIBUTING.md
- README.md
- composer.json
We plan to change default branch from "master" to "main". Some reasons behind these changes were covered by @localheinz here: https://localheinz.com/blog/2020/06/12/black-lives-matter/ 
We aim to have welcoming environment in this project, and if this change from possibly offensive language could help, then lets do it! Furthermore, the term `main` is semantically more explicit for what its used.
Also this should have minimal downsides: to notable one is for people relying on `dev-master` in composer.json, which will end with broken build. Using `dev-master` is not a good practice (constrain should be on version range, not on branch), but the only thing needed to fix this issue is in composer.json:
```diff
"require": {
-    "php-webdriver/webdriver": "dev-master"
+ …
```
> Rename default branch to main

- lib/Remote/RemoteWebElement.php
- tests/functional/RemoteWebElementTest.php
We can work around this bug in Webdriver by a
A long-standing geckodriver bug
(https://bugzilla.mozilla.org/show_bug.cgi?id=1494661) means that it is
not possible to send a key combination such as SHIFT + 'h' + NULL + 'ello'.
In this case the NULL key does not clear the SHIFT modifier as per the
specification, and it additionally prints a character for the NULL key.
It is possible to work around this bug by splitting on the encoded key
and sending the input in multiple commands instead.
Geckodriver already sends an implicity NULL at the end of the sendKeys
command which does work, does release the modifier and does not print
any character.
Send a chord, followed by a NULL to clear the modifiers, and then a subsequent value
On Chrome: Works as expected.
On Firefox (W3C): The NULL value is …
> Work around NULL key issue in sendKeys

- .github/workflows/sauce-labs.yaml
- .travis.yml
- composer.json
- tests/functional/WebDriverTestCase.php
SauceLabs tests are broken on Travis: https://travis-ci.community/t/opening-test-url-times-out-over-sauce-connect/9824/4 and are causing Travis build to fail since 27th August.
This moves them to GH Actions. Unfortunately, they will no longer by available for pull requests (because there is no sage way how to share secrets with pull request runs).
> Run SauceLabs tests via GitHub Actions

- lib/Cookie.php
- tests/unit/CookieTest.php
Fixes #705 
I tested this in a VM on Ubuntu 16.04 with the `chromium-browser` and the `chromedriver` packages:
```
Chromium 85.0.4183.83
ChromeDriver 85.0.4183.83
```
It correctly sets the values `Lax` and `Strict` (and `null` if `sameSite` is not set on the cookie). I also think I didn't come up with a good description for `setSameSite`, maybe someone comes up with a better one :)
> Add support for same-site cookies

- composer.json
- phpstan-webdriverkeys.neon
- phpstan.neon
[WebDriverKeys.php](https://github.com/php-webdriver/php-webdriver/blob/main/lib/WebDriverKeys.php#L12-L81) breaks PHPStan parallel processing, so we exclude the file first and then we analyze it separately.
Ref. https://github.com/php-webdriver/php-webdriver/pull/828#issuecomment-728001440, https://github.com/phpstan/phpstan/issues/3956 and https://github.com/clue/reactphp-ndjson/issues/21 .
> Workaround for broken PHPStan builds

- CHANGELOG.md
- lib/Remote/DriverCommand.php
- lib/Remote/HttpCommandExecutor.php
- lib/Remote/RemoteWebDriver.php
- tests/functional/RemoteWebDriverTest.php
The “New window” command (https://www.w3.org/TR/webdriver/#new-window) is not currently supported.
I’m not happy with this PR in its current form, mainly because I can’t work out the best return type, and I won’t write tests until then.
The remote endpoint returns an object containing:
- `handle`; and 
- `type` (tab, window)
In similar cases we return new objects like `WebDriverDimension` which contain the relevant data and but I’m not sure that there’s any point in returning a new `WebDriverWindow` element of any kind, because the Window performs the same as Frames - i.e. it sets the current top-level context.
I feel the best solution here is to return just the data - either just the new handle as a string, or both the handle and the type. I’m not sure if it’s worth creating a new …
> Add new window command

- composer.json
- phpstan-webdriverkeys.neon
- phpstan.neon
This reverts commit 5898a74ce2bb87b2b755d322069200c7460fe907.
PHPStan is fixed already, I just released 0.12.56.
Ref.: https://github.com/php-webdriver/php-webdriver/pull/830
> Revert "Workaround for broken PHPStan parallel processing"

- CHANGELOG.md
- lib/Exception/DriverServerDiedException.php
- lib/Remote/Service/DriverCommandExecutor.php
- tests/unit/Exception/DriverServerDiedExceptionTest.php
This PR adds a new `DriverServerDiedException` with the previous error chained to improve debugging of 'Driver server has died.' exceptions. Note that line 15 of `DriverServerDiedException` is nasty but it is needed to avoid a BC break as `DriverCommandExecutor::execute()` currently throws a `WebDriverException`. 
Alternatively a named constructor could be used in `WebDriverException` to allow injection of the previous exception. It didn't feel like it fit in this class as it isn't a driver exception but rather a process control exception. Let me know if you would prefer this.
Fixes #595.
> Add DriverServerDied exception

- lib/Chrome/ChromeDriverService.php
- lib/Remote/Service/DriverService.php
- tests/functional/Chrome/ChromeDriverServiceTest.php
Currently we require `WEBDRIVER_CHROME_DRIVER` (or deprecated `webdriver.chrome.driver`) environment variable to be set before attempting to start ChromeDriver. Even if you install `chromedriver` to your system PATH and can only start `chromedriver`, you'd still need to set the environment variable.
This PR changes this behavior, so that if you don't define you own path to executable, `ChromeDriver::start()` will by default try to execute `chromedriver` command.
Meaning you don't need to setup anything when chromedriver in already in system PATH.
> Make path to chromedriver executable not required

- lib/Remote/RemoteTargetLocator.php
- lib/Remote/RemoteWebDriver.php
- lib/WebDriverTargetLocator.php
- tests/functional/RemoteTargetLocatorTest.php
- tests/functional/RemoteWebDriverTest.php
This extends creating new window added in #799, so that you can specify intended window type (`tab` or `window`), as defined in [W3C WebDriver spec](https://w3c.github.io/webdriver/#new-window).
It seems more reasonable to have it as part of RemoteTargetLocator (not directly in RemoteWebDriver), similarly as Java bindings does. So lets move the method there and mark the previous one deprecated.
Example:
```php
// before
$driver->newWindow();
// after:
$driver->switchTo()->newWindow();
// with window type specified:
$driver->switchTo()->newWindow(WebDriverTargetLocator::WINDOW_TYPE_WINDOW); // try to open new window
// or 
$driver->switchTo()->newWindow(WebDriverTargetLocator::WINDOW_TYPE_TAB); // try to open new tab
```
**After merge:**
> Add option to specify new window type

- CHANGELOG.md
- lib/Chrome/ChromeOptions.php
- lib/Exception/ElementNotVisibleException.php
- lib/Exception/ExpectedException.php
- lib/Exception/IMEEngineActivationFailedException.php
- lib/Exception/IMENotAvailableException.php
- lib/Exception/IndexOutOfBoundsException.php
- lib/Exception/InvalidCoordinatesException.php
- lib/Exception/NoCollectionException.php
- lib/Exception/NoScriptResultException.php
- lib/Exception/NoStringException.php
- lib/Exception/NoStringLengthException.php
- lib/Exception/NoStringWrapperException.php
- lib/Exception/NoSuchCollectionException.php
- lib/Exception/NoSuchDriverException.php
- lib/Exception/NullPointerException.php
- lib/Exception/XPathLookupException.php
- lib/Remote/DesiredCapabilities.php
- lib/Remote/WebDriverBrowserType.php
- lib/WebDriverPlatform.php
- tests/unit/Remote/DesiredCapabilitiesTest.php
Its quite helpful for library users to have comment with upgrade path or with a link to more information on every deprecation.
Also, we can mark PhantomJS deprecated (it is no longer developed, headless Chrome or Firefox should be used instead), and its support from the code will be completely removed in next major version.
> Put more information to every deprecation, deprecate PhantomJS

- .github/CONTRIBUTING.md
- .github/workflows/php.yaml
- README.md
- composer.json
- tests/functional/WebDriverTestCase.php
Newly introduced GitHub [Discussions](https://github.com/php-webdriver/php-webdriver/discussions) look like a nice place to provide community support (questions, feedback, ideas etc.), so lets point users there, instead of current (unused) Facebook group and GitHub issues.
Contributor guidance in CONTRIBUTING.md was also extended.
And I've also rearranged composer scripts for better DX (developer experience).
> Add links to Discussions, improve contributor guidance and DX

- lib/Chrome/ChromeOptions.php
- tests/unit/Remote/DesiredCapabilitiesTest.php
By making the ChromeOptions and FirefoxProfile implement
JsonSerializable, both the ChromeOptions::CAPABILITY and
ChromeOptions::CAPABILITY_W3C will be serializable when converting to
JSON for the Desired Capabilities.
This also solves an issue whereby it is not possible to specify
CAPABILITY_W3C as the capability key.
Fixes #849
> Make the capability conversion JsonSerializable

- CHANGELOG.md
- lib/Chrome/ChromeDriver.php
While looking into #849 and #852, I discovered we are not passing capabilities in W3C format when staring browser via `ChromeDriver::start()`, as we do [in RemoteWebDriver::create()](https://github.com/php-webdriver/php-webdriver/blob/main/lib/Remote/RemoteWebDriver.php#L108-L113). With this PR, capabilities as submitted in both formats.
Because chromedriver accepts capabilities in new session command in both formats, **there will be no effective change** in behavior right now. But should Chromedriver team decide to remove JsonWire protocol support, creating new browser session will not work without this change. By this change, we are adding **forward compatibility**.
> Pass W3C capabilitites when starting chromedriver

- .travis.yml
- lib/Remote/RemoteWebElement.php
- tests/functional/RemoteWebElementTest.php
- tests/functional/WebDriverTestCase.php
- tests/functional/web/gecko653.html
Hi @OndraM ,
This is a bit of a weird one, and I have fixed it in the Mink driver, but I feel that others may also benefit from it too.
I can't think of a better way to address this reliably.
This issue works around a long-standing bug in Geckodriver whereby if
the first child of an anchor is a block-level element, that element
covers the click-point of the anchor. This causes an
ElementNotInteractable exception to be thrown as Marionette believes
that it cannot be scrolled into view.
The workaround to this issue is to attempt to click on an immediate
child node instead. Usually the first child will be sufficient, but if
that first child is a hidden element, then a sibling should instead be
used.
This issue has existed for several years and there is no timeframe for
fixing it upstream. …
> Work around a bug in Geckodriver (653)

- .github/workflows/sauce-labs.yaml
- .github/workflows/tests.yaml
Exclusions and conditions in tests for the old FF were already removed in #863 , so now the old-FF tests on saucelabs are failing.
> Remove Firefox 47 saucelabs build

- tests/functional/RemoteWebElementTest.php
- tests/functional/WebDriverTestCase.php
Chrome may use different color profile as a result screenshot may have inaccurate colours. (at least on MacOS).
Color should be rgb(255, 0, 0)
> forcing chrome force-color-profile=srgb

- lib/Interactions/Internal/WebDriverKeyDownAction.php
- lib/Interactions/Internal/WebDriverKeyUpAction.php
- lib/Interactions/Internal/WebDriverSingleKeyAction.php
- tests/unit/Interactions/Internal/WebDriverKeyDownActionTest.php
- tests/unit/Interactions/Internal/WebDriverKeyUpActionTest.php
- tests/unit/Interactions/Internal/WebDriverSingleKeyActionTest.php
while it's not defined in specs directly, it makes sense to throw an exception from WebDriverSingleKeyAction if key is not a modifier
Ref.:
https://github.com/SeleniumHQ/selenium/blob/e561ca8672b199ca6931b46b32290ee7ca77cf3e/java/client/src/org/openqa/selenium/interactions/internal/SingleKeyAction.java#L49
https://github.com/SeleniumHQ/selenium/blob/00de1c6b652278181721f3f4e2373b6d0088795d/javascript/node/selenium-webdriver/lib/actions.js#L59
What do you think?
To Do:
> WebDriverSingleKeyAction will throw an exception if not a modifier

- CHANGELOG.md
- README.md
- lib/Chrome/ChromeOptions.php
- lib/Firefox/FirefoxDriver.php
- lib/Firefox/FirefoxOptions.php
- lib/Remote/DesiredCapabilities.php
- tests/functional/WebDriverTestCase.php
- tests/unit/Firefox/FirefoxOptionsTest.php
- tests/unit/Remote/DesiredCapabilitiesTest.php
This adds `FirefoxOptions`, which - similarly to [ChromeOptions](https://github.com/php-webdriver/php-webdriver/wiki/Chrome#chromeoptions) - provides language-level data object to construct value of `moz:firefoxOptions`. Until now, this was possible only using multidiemensional arrays.
One nice feature is the possibility to directly pass `about:config` preferences to this object.
This also changes the way how default preferences (which we add to Firefox) are passed to the Capabilities. It is no longer via configured FirefoxProfile, but rather directly using `prefs` key in firefoxOptions, which is the recommended way. (Because of this, there is a BC layer in DesiredCapabilities, otherwise default options will be overwritten for those who already use `moz:firefoxOptions`).
📙 As part of …
> Implement FirefoxOption class

- .github/workflows/tests.yaml
- CHANGELOG.md
- lib/Chrome/ChromeDriver.php
- lib/Chrome/ChromeDriverService.php
- lib/Firefox/FirefoxDriver.php
- lib/Firefox/FirefoxDriverService.php
- lib/Local/LocalWebDriver.php
- lib/Remote/Service/DriverService.php
- tests/functional/Chrome/ChromeDriverServiceTest.php
- tests/functional/Chrome/ChromeDriverTest.php
- tests/functional/Firefox/FirefoxDriverServiceTest.php
- tests/functional/Firefox/FirefoxDriverTest.php
This adds FirefoxDriver. Now you are able to start Firefox locally without need to run `geckodriver` binary separately. The usage is [similar to ChromeDriver class](https://github.com/php-webdriver/php-webdriver/wiki/Chrome#start-directly-using-chromedriver-class).
There is also new `LocalWebDriver`, which is used as a base class for local browser drivers implementations (currently ChromeDriver and now FirefoxDriver).
Fixes #891.
```php
$driver = FirefoxDriver::start();
$driver->get('https://google.com/');
```
```php
$firefoxOptions = new FirefoxOptions();
$firefoxOptions->addArguments(['-headless']);
$capabilities = new DesiredCapabilities([FirefoxOptions::CAPABILITY => $firefoxOptions]);
$driver = FirefoxDriver::start($capabilities);
$driver->get('https://google.com/');
```
> Implement FirefoxDriver

- CHANGELOG.md
- lib/Chrome/ChromeDriver.php
- lib/Remote/RemoteWebDriver.php
- tests/functional/Chrome/ChromeDriverTest.php
As part of #892 I noticed capabilities received from the browser are not set to instance of `ChromeDriver`, when the driver is created using `ChromeDriver::start()` and we receive response to the new session command.
Instead, the driver was created with capabilities used to create the browser, which is wrong and also different behavior than is when using `RemoteWebDriver::create()`.
I also added `startUsingDriverService()` static constructor method, to make it consistent with FirefoxDriver.
> Fix browser capabilities to be set to driver instance when using ChromeDriver

- CHANGELOG.md
- lib/Remote/RemoteWebElement.php
- lib/WebDriverElement.php
- tests/functional/RemoteWebElementTest.php
- tests/functional/web/index.html
This method uses [WebDriver's Get Element Property](https://w3c.github.io/webdriver/#get-element-property) endpoint, which allows to read [IDL properties](https://developer.mozilla.org/en-US/docs/Glossary/IDL) (aka "JavaScript" properties) of on element.
Example of of the properties [can be found on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element#properties) - this includes `innerHTML`, `outerHTML`, `childElementCount` etc.
Fixes #929 . Ref. #921 #928.
> Add getDomProperty method to read JavaScript properties of elements

- lib/Remote/RemoteWebElement.php
According to W3C Specs, [getElementAttribute()](https://w3c.github.io/webdriver/#get-element-attribute) will return `true`, `null` or element value (which will be string, in case of attribute).
And `getDomProperty()` could return [according to specs](https://w3c.github.io/webdriver/#get-element-property) either `null` or "value of property" which does not guarantee anything about type, so lets just use mixed.
> Fix phpdoc for getAttribute and getDomProperty to match the specs

- lib/Cookie.php
This throws deprecation messages when running on PHP 8.1. Because this library also supports very old php versions I guess we cannot just set return types.
> Fix PHP 8.1 deprecations in the Cookie class

- .php-cs-fixer.dist.php
- lib/Cookie.php
Adding PHPDoc return and param types to ArrayAccess methods, to suppress deprecation warnings in Symfony 5.4/PHP7.4
Pretty sure this should fix for 8.1 (don't have for test here), leaving #958 unnecessary.
> Add return and param type annotations to Cookie.php to supress deprecations

- README.md
The linked site for Chromedriver will soon be deprecated. Adding link to the latest site.
> Removing link to deprecated site

- lib/Remote/RemoteWebDriver.php
See issue in #986 . The `GET /sessions` endpoint is not part of W3C WebDriver, because of security reasons (so that you cannot get and steal other session id).
Although some remote ends (chromedriver) implement it, it is no longer part of the standard. If someone want to call the command eg. on Chromedriver without deprecation warnings (but on its own responsibility), it could still be achieved using [custom commands](https://github.com/php-webdriver/php-webdriver/wiki/Custom-commands).
```php
$sessions = $driver->executeCustomCommand(
'/sessions',
'GET'
);
// ...
```
> Mark getAllSessions() deprecated in W3C WebDriver

- CHANGELOG.md
- lib/Remote/RemoteWebDriver.php
- lib/Remote/RemoteWebElement.php
- lib/Support/ScreenshotHelper.php
- tests/functional/RemoteWebDriverTest.php
- tests/functional/RemoteWebElementTest.php
- tests/unit/Support/ScreenshotHelperTest.php
Apart from separating screenshot/filesystem logic from two places, this should better handle errors and solve #969 and #983.
The previous behavior was to silently ignore if screenshot command returned empty data. This will now throw an `WebDriverException`.
> Separate takeScreenshot logic to better handle errors and to fix PHP 8.1 deprecations

- .github/workflows/tests.yaml
I wanted to use 4.4.0, but there seems to be [performance regression between 4.3.0 and 4.4.0](https://github.com/SeleniumHQ/selenium/issues/10984), causing the 2 minutes job to run for almost 40 minutes, which is not ideal. So lets use 4.3.0 for now.
> Run functional tests on Selenium server 4.3

- CHANGELOG.md
- lib/Chrome/ChromeOptions.php
- lib/Firefox/FirefoxDriver.php
- lib/Firefox/FirefoxOptions.php
- lib/Firefox/FirefoxProfile.php
- tests/functional/Firefox/FirefoxDriverTest.php
- tests/functional/Firefox/FirefoxProfileTest.php
Add `setProfile()` method to Firefox, so that setting Firefox Profile is straightforward and type-safe:
```diff
$profile = new FirefoxProfile();
$firefoxOptions = new FirefoxOptions();
-$firefoxOptions->setOption('profile', $profile->encode());
+$firefoxOptions->setProfile($profile);
```
Also setting the profile directly to Capabilities using `FirefoxDriver::PROFILE` constant like this is now deprecated (it is also not W3C WebDriver compatible, because it is not in the vendor namespace):
```php
$profile = new FirefoxProfile();
$capabilities = DesiredCapabilities::firefox();
$capabilities->setCapability(FirefoxDriver::PROFILE, $profile); // deprecated, use $firefoxOptions->setProfile($profile) as above
```
---
> Firefox profile improvements

- CHANGELOG.md
- lib/Remote/RemoteWebDriver.php
- tests/unit/Remote/RemoteWebDriverTest.php
In some hard-to-reproduce scenarios, remote end returns response, however, it contains `null` in value (or does not contain value at all). This causes php-webdriver to fail on fatal/type error. 
Instead, `UnknownErrorException` will be throw, to allow better debugging.
Fixes #944, replaces #945
> Throw exception instead of fatal error on invalid server response

- README.md
The W3C DebDriver support in php-webdriver is probably better then support for JsonWire ever was, so its unnecessary to describe it as "experimental".
Also fixed few http links
> Update readme, as the W3C WebDriver support is not experimental

- lib/Exception/DetachedShadowRootException.php
- lib/Exception/NoSuchShadowRootException.php
- lib/Exception/WebDriverException.php
- lib/Remote/DriverCommand.php
- lib/Remote/HttpCommandExecutor.php
- lib/Remote/RemoteWebElement.php
- lib/Remote/ShadowRoot.php
- lib/Support/Events/EventFiringWebElement.php
- lib/WebDriverElement.php
- lib/WebDriverSearchContext.php
- phpstan.neon
- tests/functional/ShadowDomTest.php
- tests/functional/web/index.html
- tests/functional/web/web_components.html
This PR adds [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) support. Fixes #1003 .
Shadow DOM is essential part of Web Components, as it encapsulates the component DOM and styles. This component isolation however mean one cannot access elements which are encapsulated in shadow DOM of a component with usual `$driver->findElement()` and `$driver->findElements()` method. You will basically not by able to find those elements in the default DOM.
Because of this, W3C WebDriver [added support](https://github.com/w3c/webdriver/pull/1565) for endpoints specifically made for accessing Shadow DOM elements.
So far, this has been implemented in Chromedriver and partially in Geckodriver.
```php
// consider having web component …
```
> Implement Shadow DOM support

- CHANGELOG.md
- composer.json
- lib/Remote/RemoteWebDriver.php
- lib/Remote/RemoteWebElement.php
- lib/Support/IsElementDisplayedAtom.php
- lib/scripts/isElementDisplayed.js
- tests/functional/RemoteWebElementTest.php
This PR adds support for `RemoteWebElement::isDisplayed()` method even for remote ends, which does not provide the `/displayed` endpoint.
This is because W3C WebDriver does not specify this endpoint (see https://w3c.github.io/webdriver/#element-displayedness ), and only some of the vendors (namely Chromedriver and Geckodrive) choose to implement is by themselves. Other, however, do not provide this feature (like Safari), meaning the `isDisplayed()` was not working here, as noted in #843 
For these cases, we use javascript atom, which provides the feature. This behavior is consistent with official Java/JavaScript/Ruby etc. bindings.
The Atom we used is adopted [from Webdriver.io](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/scripts/isElementDisplayed.ts) …
> Add element isDisplayed support even for browsers without native support

- tests/functional/Firefox/FirefoxProfileTest.php
It sometimes takes split of a second for the extension to render the element causing the test to fail from time to time. This will be fixed using explicit wait.
> Fix firefox extension test flakiness

- CHANGELOG.md
- lib/Remote/RemoteWebDriver.php
Workaround for #1022 .
This is fix only for branch 1.13, as I'm, working on further refactoring for 1.14.
> Do not fail in isDisplayed call when capabilities are missing

- .github/workflows/sauce-labs.yaml
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: saucelabs/sauce-connect-action, saucelabs/sauce-connect-action
> Update sauce connect action

- .github/workflows/tests.yaml
- CHANGELOG.md
- lib/Exception/Internal/UnexpectedResponseException.php
- lib/Remote/RemoteWebDriver.php
- phpstan.neon
- tests/functional/RemoteWebDriverCreateTest.php
- tests/functional/WebDriverTestCase.php
- tests/unit/Remote/RemoteWebDriverTest.php
This is a proper fix for issues like #1022 etc.
When RemoteWebDriver instance was created using `createBySessionID()`, it was missing value of capabilities (it was null). This lead to various unexpected issues, for example with instance crated like this, you are not able to get the name of the running browser. Which is unexpected, not type-safe and leading to errors.
With this PR, we try to read capabilities from Selenium Grid server (there is no endpoint defined in W3C WebDriver, it is only the API of Selenium Server itself). Alternatively, if you don't use Selenium Grid, you must explicitly provide capabilities using the sixth parameter of `createBySessionID()`, see example. Thank to this, you can always be sure `$driver->getCapabilities()`, …
> Improve session reusing, require capabilities to be set

- lib/Remote/Service/DriverService.php
Minimal required version of Symfony is now 5, so no need to keep compatibility layer <3.3 :)
> Remove no longer needed compatibility layer with old Symfony

- CHANGELOG.md
- lib/Chrome/ChromeOptions.php
- lib/Remote/DesiredCapabilities.php
- tests/unit/Remote/DesiredCapabilitiesTest.php
We already have `ChromeOptions::CAPABILITY_W3C` and we convert ChromeOptions::CAPABILITY and ChromeOptions::CAPABILITY_W3C differently for OSS and W3C NewSession payload.
However, this breaks things in new ChromeDriver (#1061), so we will now use W3C compatible `goog:chromeOptions` for both and we will no longer attempt to merge the values. This should not break anything, as this is supported by Chrome since 2017, see https://bugs.chromium.org/p/chromedriver/issues/detail?id=1786 .
> Replace ChromeOptions::CAPABILITY with W3C compatible value

- lib/WebDriverSelect.php
- tests/functional/WebDriverSelectTest.php
- tests/functional/web/form.html
This commit updates WebDriverSelectTest.php to provide support for selecting multiple selectors. 
It extends the testShouldCreateNewInstanceForSelectElementAndDetectIfItIsMultiple() function with a data provider to test multiple select elements.
The changes also include corrections to WebDriverSelect.php to properly adhere to spec for Boolean attributes, by ensuring that the attribute value is 'true' or 'multiple'. 
Additional select options have also been added to the form.html file to support the new tests.
https://html.spec.whatwg.org/#boolean-attributes
> Update WebDriverSelect test to support multiple selectors

- .github/workflows/tests.yaml
- lib/Interactions/Internal/WebDriverCoordinates.php
- lib/Local/LocalWebDriver.php
The path [is now different](https://github.com/actions/runner-images/blob/ubuntu22/20230724.1/images/linux/Ubuntu2204-Readme.md#environment-variables-1) and the tests are now failing with
`Facebook\WebDriver\Exception\Internal\IOException: File is not executable. Make sure the path is correct or use environment variable to specify location of the executable. ("/usr/local/share/chrome_driver/chromedriver")`
> Fix path to chromedriver in tests on latest Ubuntu

- composer.json
Symfony 7 should be available next month (November 2023): https://symfony.com/releases/7.0 and it would be great if we can start testing `php-webdriver` using upcoming Symfony 7.
> Add support for Symfony Process 7

- tests/functional/Chrome/ChromeDriverTest.php
- tests/functional/WebDriverTestCase.php
https://developer.chrome.com/blog/chrome-headless-shell
This fixes failing builds, because the "old" headless chrome reports its name as "chrome-headless-shell", not chrome, breaking some tests.
> Use new Chrome headless mode instead of old chrome-headless-shell

- tests/functional/RemoteWebDriverCreateTest.php
Looks like SauceLabs fixed the issue, so we need to remove the workaround.
https://github.com/php-webdriver/php-webdriver/actions/runs/7852184530/job/21430248871#step:7:36
> Test: Remove SauceLabs workaround for MS Edge

- lib/Remote/RemoteWebElement.php
A couple of methods that are returning $this in the RemoteWebElement class are marked as returning an instance of RemoteWebElement itself when in fact they return a static/$this instance when the RemoteWebElement class is extended. This PR fixes those, so static analysis understands the extended class.
> Fix static return types in RemoteWebElement

- tests/functional/Chrome/ChromeDriverTest.php
- tests/functional/WebDriverTestCase.php
The pop-up windows starts to appear with Chrome 127+ in EU and EEA and it blocks view on the tested page (but the tests run ok, just the view is blocked by the pop-up).
> Disable search engine selection pop-up in tests for chrome 127+ 

- tests/functional/ShadowDomTest.php
- tests/functional/web/web_components.html
Chromedriver now provides implicit access to shadow root for all input elements in a closed mode (instead of throwing an NoSuchShadowRootException).  This breaks our tests. See https://issues.chromium.org/issues/372834222
Also Geckodriver already supports Shadow dom, meaning we can enable these tests. See https://github.com/mozilla/geckodriver/issues/2005
> Fix shadow dom tests

- .github/CONTRIBUTING.md
- .github/workflows/tests.yaml
- tests/functional/WebDriverTestCase.php
- defines new env var (`DISABLE_HEADLESS`) to specifically enable/disable headless mode
- by default headless is enabled (for BC reasons)
- documented in the same place `BROWSER_NAME` is documented
> Allow running tests in headfull mode (useful for testing)

- lib/Exception/PhpWebDriverExceptionInterface.php
Currently, `PhpWebDriverExceptionInterface` does not extend `\Throwable`, making it difficult to catch exceptions by the interface while still accessing common exception methods like `getMessage()`, etc. This PR fixes that by extending `\Throwable`, so exceptions can be handled more easily.
> Add Throwable extension to PhpWebDriverExceptionInterface
