php-webdriver/php-webdriver

composer.json, lib/remote/HttpCommandExecutor.php, lib/remote/RemoteWebDriver.php
=> Correct timeout typo

lib/WebDriverWait.php, lib/interactions/internal/WebDriverMouseAction.php, lib/remote/HttpCommandExecutor.php, lib/remote/service/DriverService.php
As requested on #214.
Here's it @gfosco.
:beer:
=> Few improvements, avoiding some elses

.travis.yml
=> Enhancement: Specify environment variable in env section of Travis configuration

lib/Remote/HttpCommandExecutor.php, lib/Remote/RemoteWebDriver.php
Supports tests running on a remote server that's behind a proxy
=> Added http proxy and port vars

lib/WebDriverSearchContext.php, lib/WebDriverSelect.php
=> improved some @return type docs

tests/unit/WebDriverButtonReleaseActionTest.php, tests/unit/WebDriverClickActionTest.php, tests/unit/WebDriverClickAndHoldActionTest.php, tests/unit/WebDriverContextClickActionTest.php, tests/unit/WebDriverCoordinatesTest.php, tests/unit/WebDriverDoubleClickActionTest.php, tests/unit/WebDriverKeyDownActionTest.php, tests/unit/WebDriverKeyUpActionTest.php, tests/unit/WebDriverMouseMoveActionTest.php, tests/unit/WebDriverMouseToOffsetActionTest.php, tests/unit/WebDriverSendKeysActionTest.php
As discussed here:
https://github.com/facebook/php-webdriver/issues/242
=> unit tests wrong namespace deletion

composer.json, lib/Firefox/FirefoxProfile.php
Added possibility to set RDF file
Added possibility to add datas for extensions
Added prefix to extension temporary directory to follow the others temporary directory
=> Improvements in FirefoxProfile

lib/WebDriverWait.php
=> Check isset for timeout in seconds

composer.json, lib/Chrome/ChromeOptions.php, lib/Firefox/FirefoxDriver.php, lib/Firefox/FirefoxPreferences.php, lib/Firefox/FirefoxProfile.php, lib/Remote/DesiredCapabilities.php, lib/Remote/DriverCommand.php, lib/Remote/RemoteWebDriver.php, lib/Remote/Service/DriverCommandExecutor.php, lib/Remote/WebDriverBrowserType.php, lib/Remote/WebDriverCapabilityType.php, lib/Remote/WebDriverCommand.php, lib/WebDriverPlatform.php, phpunit.xml.dist, tests/unit/Interactions/Internal/WebDriverButtonReleaseActionTest.php, tests/unit/Interactions/Internal/WebDriverClickActionTest.php, tests/unit/Interactions/Internal/WebDriverClickAndHoldActionTest.php, tests/unit/Interactions/Internal/WebDriverContextClickActionTest.php, tests/unit/Interactions/Internal/WebDriverCoordinatesTest.php, tests/unit/Interactions/Internal/WebDriverDoubleClickActionTest.php, tests/unit/Interactions/Internal/WebDriverKeyDownActionTest.php, tests/unit/Interactions/Internal/WebDriverKeyUpActionTest.php, tests/unit/Interactions/Internal/WebDriverMouseMoveActionTest.php, tests/unit/Interactions/Internal/WebDriverMouseToOffsetActionTest.php, tests/unit/Interactions/Internal/WebDriverSendKeysActionTest.php, tests/unit/Remote/DesiredCapabilitiesTest.php, tests/unit/Remote/WebDriverCommandTest.php
Unit-tests were reorganized, so that their structure matches structure of the projects (what is usual in modern projects). Unit tests for `WebDriverCommand` and `DesiredCapabilities` was added.
Also some minor codestyle improvements (mainly missing phpdoc) were made.
Last but not least, class `FirefoxPreferences` with constants of common Firefox profile settings was added.
=> Improve unit tests & codestyle

CHANGELOG.md, README.md
See #275. CHANGELOG.md was added (and readme was cleaned up a bit). To the changelog I also added what was changed in last 2 releases.
Contribution guidelines update will follow later in separate PR.
=> Add a changelog, cleanup readme

CHANGELOG.md, CONTRIBUTING.md, README.md, phpunit.xml.dist
Ref #275, #277.
Contribution guidelines separated from changelog to  CONTRIBUTING.md (what is [github.com standard](https://github.com/blog/1184-contributing-guidelines), and would make it appear before creating PR/issue).
Any more ideas? Should something be added/modified?
=> Contribution guidelines

lib/Firefox/FirefoxProfile.php, lib/Remote/Service/DriverService.php, tests/functional/WebDriverTestCase.php, tests/functional/html/upload.html
[+]: fixed function-call from "$checker->waitUntilUnAvailable()" -> "$checker->waitUntilUnavailable()"
[~]: "\t" -> spaces
[~]: "dirname(__FILE__)" -> "__DIR__"
[*]: "<input></input>" -> <input />
=> fixed some small code-smells (reported by PhpStorm)

README.md
Fixing this issue https://github.com/facebook/php-webdriver/issues/283
=> Updated Readme to fix DesiredCapabilities link

CHANGELOG.md, composer.json
As suggested correctly in #279
=> Added ext-curl as dependency

lib/Firefox/FirefoxProfile.php
Fixed installedExtension() in FirefoxProfile.php to remove hardcoded namespace prefix.
We now find the what namespace if any we need to use for the 'id' element before searching for it.
=> Fixed issue #301 - Hardcoded 'em' namespace in installExtension() prevents some extensions from loading

CONTRIBUTING.md
The link to the official Java API was broken
=> Edited the link to the official Java API

lib/Chrome/ChromeDriver.php, lib/Interactions/Internal/WebDriverCoordinates.php, lib/Interactions/Internal/WebDriverKeysRelatedAction.php, lib/Interactions/Internal/WebDriverMouseAction.php, lib/Interactions/Internal/WebDriverMoveToOffsetAction.php, lib/Interactions/Internal/WebDriverSendKeysAction.php, lib/Interactions/Internal/WebDriverSingleKeyAction.php, lib/Interactions/Touch/WebDriverDownAction.php, lib/Interactions/Touch/WebDriverFlickAction.php, lib/Interactions/Touch/WebDriverFlickFromElementAction.php, lib/Interactions/WebDriverActions.php, lib/Interactions/WebDriverCompositeAction.php, lib/Remote/DesiredCapabilities.php, lib/Remote/RemoteExecuteMethod.php, lib/Remote/RemoteTargetLocator.php, lib/Remote/RemoteWebDriver.php, lib/Remote/RemoteWebElement.php, lib/Remote/UselessFileDetector.php, lib/Support/Events/EventFiringWebDriver.php, lib/Support/Events/EventFiringWebElement.php, lib/WebDriverAlert.php, lib/WebDriverBy.php, lib/WebDriverDimension.php, lib/WebDriverElement.php, lib/WebDriverExpectedCondition.php, lib/WebDriverOptions.php, lib/WebDriverTimeouts.php, lib/WebDriverWait.php, lib/WebDriverWindow.php
Multiple typehint fixes and improvements. 
Also callable is used instead of Closure typehinting, so that even non-anonymous functions could be passed.
=> Add and fix typehints

lib/Chrome/ChromeDriver.php, lib/Remote/RemoteWebDriver.php
See #350 - the `$url` variable name confuses user about its meaning.
=> Clarify meaning of selenium server URL variable of RemoteWebDriver

CHANGELOG.md, lib/WebDriverExpectedCondition.php, tests/unit/WebDriverExpectedConditionTest.php
=> New URL related conditions

lib/Remote/RemoteWebDriver.php, lib/WebDriverTimeouts.php, tests/functional/WebDriverTimeoutsTest.php, tests/functional/web/delayed_element.html, tests/functional/web/index.html, tests/functional/web/slow_loading.html, tests/functional/web/slow_pixel.png.php, tests/unit/WebDriverOptionsTest.php
Also related to #363 - the tests are passing (tested on Firefox 47, Firefox 51, Chrome, HtmlUnit), so there should be a bug,
=> Functional tests for WebDriverTimeouts

.travis.yml, tests/functional/FileUploadTest.php, tests/functional/RemoteWebDriverCreateTest.php, tests/functional/RemoteWebDriverFindElementTest.php, tests/functional/RemoteWebDriverTest.php, tests/functional/RemoteWebElementTest.php, tests/functional/WebDriverAlertTest.php, tests/functional/WebDriverByTest.php, tests/functional/WebDriverSelectTest.php, tests/functional/WebDriverTestCase.php, tests/functional/WebDriverTimeoutsTest.php
Thanks to [SauceLabs](https://saucelabs.com/open-source), we can run functional tests against their cloud of platforms and browsers, allowing us to make sure the php-webdriver library is compatible with them.
The tests results will be publicly available here: https://saucelabs.com/u/php-webdriver
=> Run functional tests on SauceLabs

.travis.yml
It was finally released last week :). And contains once again fixed htmlunit.
=> Upgrade to Selenium 3.1.0

.travis.yml, composer.json, phpunit.xml.dist, tests/functional/RemoteWebDriverTest.php, tests/functional/ReportSauceLabsStatusListener.php, tests/functional/WebDriverTestCase.php
To see the test results on the public SauceLabs dashboard.
=> Report test results to SauceLabs API

CHANGELOG.md, lib/Interactions/WebDriverCompositeAction.php, lib/WebDriverKeys.php, tests/unit/WebDriverKeysTest.php
=> Do not throw fatal error when null is passed to sendKeys (fixes #419)

.travis.yml, tests/functional/FileUploadTest.php, tests/functional/RemoteWebDriverFindElementTest.php, tests/functional/RemoteWebElementTest.php, tests/functional/WebDriverAlertTest.php, tests/functional/WebDriverSelectTest.php, tests/functional/WebDriverTestCase.php
Chrome Headless was introduced with Chrome 59: https://developers.google.com/web/updates/2017/04/headless-chrome
We also add MS Edge, as it looks quite stable (except few issues - see skipped tests).
=> Add headless Chrome on Travis + MS Edge on SauceLabs

lib/Firefox/FirefoxDriver.php, lib/Firefox/FirefoxPreferences.php, lib/Remote/DriverCommand.php, lib/Remote/WebDriverBrowserType.php, lib/Remote/WebDriverCapabilityType.php, lib/WebDriverNavigation.php, lib/WebDriverPlatform.php, tests/functional/RemoteWebDriverTest.php, tests/functional/WebDriverNavigationTest.php, tests/functional/WebDriverTimeoutsTest.php
This part of an effort to add more functional tests in order to increase code coverage before we start implementing the W3C protocol ( https://github.com/facebook/php-webdriver/issues/469).
=>  Add functional tests for WebDriverNavigation 

lib/Interactions/WebDriverCompositeAction.php, tests/functional/WebDriverActionsTest.php, tests/functional/web/events.html, tests/functional/web/index.html
We also need some regression tests for actions when implementing #469 .
=> Add functional tests for basic actions (click, double click, context click)

.travis.yml, composer.json, tests/functional/Chrome/ChromeDriverServiceTest.php, tests/functional/Chrome/ChromeDriverTest.php
To make sure eg. #489 is working properly.
cc @VolCh
=> Add tests for ChromeDriverService and ChromeDriver

lib/WebDriverSelectInterface.php
fixed https://travis-ci.org/facebook/php-webdriver/jobs/296256023 with new version of php-cs-fixer
=> Fix code style

lib/WebDriverElement.php
=> PHPDoc: WebDriverElement::getAttribute may return null

.php_cs.dist, composer.json, tests/unit/Remote/DesiredCapabilitiesTest.php
Some changes requested in your review of #545 can be automatically detected and fixed by PHP CS Fixer.
I updated the config accordingly.
I hope it will save you some time during next reviews :)
=> Complete the PHP CS Fixer config

example.php, tests/bootstrap.php
New tooling internally flags any code files without the header...
=> Added copyright headers to 2 codefiles

lib/Exception/IndexOutOfBoundsException.php, lib/Exception/NoCollectionException.php, lib/Exception/NoStringException.php, lib/WebDriverSelectInterface.php, tests/functional/web/slow_pixel.png.php, tests/functional/web/submit.php, tests/functional/web/upload.php
A few more popped up in a full scan, related to #608
=> Added a few more copyright headers.

lib/Remote/HttpCommandExecutor.php, tests/functional/WebDriverWindowTest.php
https://w3c.github.io/webdriver/#resizing-and-positioning-windows
Luckily the command are similar to those on JsonWire, just have different path (and share the same command for size and position).
=> Add W3C window size and position commands

.travis.yml, lib/Remote/RemoteWebElement.php, tests/functional/FileUploadTest.php, tests/functional/WebDriverAlertTest.php, tests/functional/WebDriverCheckboxesTest.php, tests/functional/WebDriverRadiosTest.php, tests/functional/WebDriverTestCase.php, tests/functional/WebDriverTimeoutsTest.php
Chrome and MicrosoftEdge on Sauce Labs builds now uses W3C protocol. :muscle:
=> Use W3C protocol on part of Sauce Labs builds 

lib/Remote/DesiredCapabilities.php, lib/Remote/RemoteWebDriver.php, tests/functional/RemoteWebDriverCreateTest.php
=> Accept W3C capabilitites from the browser and provide them as OSS ones

CHANGELOG.md, lib/Chrome/ChromeDriverService.php, tests/functional/Chrome/ChromeDriverServiceTest.php, tests/functional/Chrome/ChromeDriverTest.php
=> Change environment variable defining path to ChromeDriver executable

.travis.yml, lib/Remote/RemoteKeyboard.php, lib/Remote/RemoteWebDriver.php, lib/WebDriverKeys.php, tests/functional/RemoteKeyboardTest.php, tests/functional/WebDriverActionsTest.php, tests/functional/WebDriverAlertTest.php, tests/functional/web/events.html, tests/functional/web/form.html
=> Implement W3C compatible RemoteKeyboard 

.travis.yml, composer.json, lib/WebDriverExpectedCondition.php, phpstan.neon
Also replace mock-objects with PHP 5.6-7.4 compatible fork sminnee/phpunit-mock-objects
=> Add PHP 7.4 Travis build

CHANGELOG.md, lib/Remote/DriverCommand.php, lib/Remote/HttpCommandExecutor.php, lib/Remote/RemoteWebElement.php, lib/WebDriverElement.php, tests/functional/RemoteWebElementTest.php
This PR add a new method takes a screenshot of specific element.
(Previous PR=#515)
ISSUE=#513
=> Add take element screenshot command

lib/Remote/HttpCommandExecutor.php, lib/Remote/RemoteTargetLocator.php, lib/WebDriverTargetLocator.php, tests/functional/RemoteTargetLocatorTest.php
=> Add switch to parent frame command

CONTRIBUTING.md, README.md, composer.json, tests/functional/RemoteWebDriverTest.php, tests/functional/web/index.html
Repository was transferred, so this is just the first quick change (see #730)
=> Rename repository to php-webdriver/php-webdriver

.github/CONTRIBUTING.md, README.md, composer.json
This will be merged right after `community` branch is renamed to `master`.
See #739
=> Change community branch to master

README.md, example.php
To have everything nicely prepared for 1.8.0.
Any suggestions what could be missing in the readme?
=> Extend and improve readme

lib/Remote/RemoteWebElement.php
Replaces #747 .
https://github.com/w3c/webdriver/issues/1355
=> Attempt to upload the file to the remote browser even in W3C mode

CHANGELOG.md, lib/Remote/RemoteWebElement.php, lib/WebDriverKeys.php, tests/functional/RemoteWebElementTest.php, tests/unit/WebDriverKeysTest.php
=> Fix sendKeys not accepting array as input

.gitattributes
=> Clean up some files from dist version

lib/Chrome/ChromeDriver.php, lib/Remote/RemoteWebDriver.php, tests/functional/RemoteWebDriverCreateTest.php
=> Fix RemoteWebDriver cannot be instantiated without second parameter

lib/Remote/RemoteWebElement.php
=> Minor improvements and typos fixes

lib/Chrome/ChromeOptions.php, lib/Remote/DesiredCapabilities.php, tests/unit/Remote/DesiredCapabilitiesTest.php
This is an alternative fix for #732
=> making sure that chromeOptions is an object when empty

lib/Chrome/ChromeDevToolsDriver.php, lib/Chrome/ChromeDriver.php, lib/Remote/RemoteWebDriver.php, lib/WebDriver.php, tests/functional/Chrome/ChromeDevToolsDriverTest.php, tests/functional/Chrome/ChromeDriverTest.php
This adds ability to execute Chrome DevTool Protocol (CDP) commands via Chromedriver HTTP endpoint.
Unlike in previous implementation in #556 , access to CDP is encapsulated to stand-alone class `ChromeDevToolsDriver`, which provide access to CDP not only from ChromeDriver instance (= Chrome running on the local machine), but also when Chrome is running remotely via Selenium.
```php
// local Chrome
$driver = ChromeDriver::start();
$devTools = $driver->getDevTools(); // return ChromeDevToolsDriver instance
$devTools->execute('Performance.enable');
```
```php
// remote Chrome
$driver = RemoteWebDriver::create('...', DesiredCapabilities::chrome());
$devToolsDriver = new ChromeDevToolsDriver($driver);
$devToolsDriver->execute('Performance.enable');
```
Class `ChromeDevToolsDriver` is open for …
=> Execute Chrome DevTool Protocol (CDP) commands

.travis.yml
See https://github.com/mozilla/geckodriver/releases/
=> Update build to latest Geckodriver 0.28.0

.github/CONTRIBUTING.md, .github/workflows/php.yaml, CODE_OF_CONDUCT.md, README.md
Add more link to wiki, where some part of README were also moved and extended.
=> Improve readme, add more wiki links

tests/unit/WebDriverExpectedConditionTest.php
While working on transferring unit tests from Travis to GH Actions, I noticed these PHPUnit deprecations of `at()` matcher.
See https://github.com/sebastianbergmann/phpunit/issues/4297
=> Remove phpunit deprecations

.github/ISSUE_TEMPLATE/bug_report.md
Another attempt to try to avoid bugreports without the template.
Also added more explanations how to get versions of all relevant components.
=> Improve bug template

lib/Remote/RemoteWebElement.php
With previous implementation some edge cases were not properly covered. This seems to be working better.
Inspired by [polyfill in java bindings](https://github.com/SeleniumHQ/selenium/blob/64447d4b03f6986337d1ca8d8b6476653570bcc1/java/client/src/org/openqa/selenium/remote/codec/w3c/W3CHttpCommandCodec.java#L385-L394), but updated to use `Event` constructor.
Unfortunately I don't have a test-case - found this issue on proprietary React-based component. But this implementation seems to be working OK, so if nothing breaks in current tests, we can guess it is working at-least  as the previous version.
=> Improve submit event polyfill for W3C protocol

scripts/doctum.php
=> Fix #977 - broken open-search URL

CHANGELOG.md, lib/Remote/HttpCommandExecutor.php
See https://github.com/php-webdriver/php-webdriver/issues/859#issuecomment-1234388188
=> Increase default request timeout to 3 minutes

lib/Remote/RemoteWebElement.php, tests/functional/RemoteWebElementTest.php, tests/functional/web/index.html
Add functional test for isDisplayed method.
Related to #843.
=> Add isDisplayed test

.github/workflows/tests.yaml, README.md
See https://github.com/badges/shields/issues/8671
=> Use new shields.io badges URL

.github/workflows/tests.yaml, .php-cs-fixer.dist.php, lib/Chrome/ChromeDriver.php, lib/Exception/Internal/DriverServerDiedException.php, lib/Firefox/FirefoxDriver.php, lib/Interactions/Internal/WebDriverKeysRelatedAction.php, lib/Interactions/Internal/WebDriverMouseAction.php, lib/Interactions/Internal/WebDriverMoveToOffsetAction.php, lib/Interactions/Internal/WebDriverSendKeysAction.php, lib/Interactions/Internal/WebDriverSingleKeyAction.php, lib/Interactions/Touch/WebDriverTouchAction.php, lib/Interactions/WebDriverActions.php, lib/Local/LocalWebDriver.php, lib/Remote/RemoteMouse.php, lib/Remote/RemoteWebDriver.php, lib/Support/Events/EventFiringWebDriver.php, lib/WebDriverEventListener.php, tests/functional/Firefox/FirefoxDriverTest.php, tests/functional/WebDriverByTest.php
=> Support PHP 8.4
